<a href="https://colab.research.google.com/github/Aswini-Raj/ML_Algorithms/blob/main/Market_Basket_Analysis_Using_the_ECLAT_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('/content/drive/MyDrive/Market_Basket_Optimisation.csv', header=None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
transactions=[]
for i in range(0,len(df)):
  transactions.append([str(df.values[i,j])for j in range(0,20) if str(df.values[i,j])!='NaN'])

In [4]:
def eclat(transactions, min_support):

    item_tid = defaultdict(set)

    # Build vertical format
    for tid, transaction in enumerate(transactions):
        for item in transaction:
            item_tid[item].add(tid)

    def recursive(prefix, items):
        results = []
        items = list(items.items())

        for i in range(len(items)):
            item_i, tid_i = items[i]

            new_prefix = prefix + [item_i]
            support = len(tid_i)

            if support >= min_support:
                results.append((new_prefix, support))

                suffix = {}

                for j in range(i + 1, len(items)):
                    item_j, tid_j = items[j]
                    intersection = tid_i & tid_j

                    if len(intersection) >= min_support:
                        suffix[item_j] = intersection

                results.extend(recursive(new_prefix, suffix))

        return results

    return recursive([], item_tid)

In [ ]:
from collections import defaultdict
min_support = 2

results = eclat(transactions, min_support)

for itemset, support in results:
    print(itemset, support)

Streaming output truncated to the last 5000 lines.
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'spaghetti', 'tomatoes'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'spaghetti', 'tomatoes', 'protein bar'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'spaghetti', 'protein bar'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'spaghetti', 'pancakes'] 3
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'spaghetti', 'pancakes', 'french wine'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'spaghetti', 'french wine'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'chocolate'] 3
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'chocolate', 'pancakes'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'chicken'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'fresh tuna'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'fresh tuna', 'cake'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'tomatoes'] 3
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'tomatoes', 'protein bar'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'tomatoes', 'cake'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'protein bar'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'pancakes'] 3
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'pancakes', 'french wine'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'grated cheese'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'ground beef'] 2
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'cake'] 3
['olive oil', 'burgers', 'nan', 'frozen vegetables', 'french wine'] 2
['olive oil', 'burgers', 'nan', 'spaghetti'] 21
['olive oil', 'burgers', 'nan', 'spaghetti', 'cooking oil'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate'] 12
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'fresh tuna'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'fresh tuna', 'parmesan cheese'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'ham'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'ham', 'pancakes'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'ham', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'ham', 'cake'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'pancakes'] 7
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'pancakes', 'cake'] 3
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'pancakes', 'muffins'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'grated cheese'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'parmesan cheese'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'ground beef'] 3
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'ground beef', 'cake'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'cake'] 5
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'cake', 'muffins'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'muffins'] 3
['olive oil', 'burgers', 'nan', 'spaghetti', 'chocolate', 'french wine'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'chicken'] 4
['olive oil', 'burgers', 'nan', 'spaghetti', 'fresh tuna'] 3
['olive oil', 'burgers', 'nan', 'spaghetti', 'fresh tuna', 'grated cheese'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'fresh tuna', 'parmesan cheese'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'tomatoes'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'tomatoes', 'protein bar'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'protein bar'] 3
['olive oil', 'burgers', 'nan', 'spaghetti', 'ham'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'ham', 'pancakes'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'ham', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'ham', 'cake'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'pancakes'] 9
['olive oil', 'burgers', 'nan', 'spaghetti', 'pancakes', 'cake'] 4
['olive oil', 'burgers', 'nan', 'spaghetti', 'pancakes', 'muffins'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'pancakes', 'french wine'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'grated cheese'] 3
['olive oil', 'burgers', 'nan', 'spaghetti', 'parmesan cheese'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'ground beef'] 4
['olive oil', 'burgers', 'nan', 'spaghetti', 'ground beef', 'cake'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'cake'] 6
['olive oil', 'burgers', 'nan', 'spaghetti', 'cake', 'muffins'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'hot dogs'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'muffins'] 3
['olive oil', 'burgers', 'nan', 'spaghetti', 'gums'] 3
['olive oil', 'burgers', 'nan', 'spaghetti', 'gums', 'french wine'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'french wine'] 4
['olive oil', 'burgers', 'nan', 'spaghetti', 'french wine', 'salt'] 2
['olive oil', 'burgers', 'nan', 'spaghetti', 'salt'] 2
['olive oil', 'burgers', 'nan', 'cooking oil'] 4
['olive oil', 'burgers', 'nan', 'cooking oil', 'chocolate'] 3
['olive oil', 'burgers', 'nan', 'cooking oil', 'chocolate', 'pancakes'] 2
['olive oil', 'burgers', 'nan', 'cooking oil', 'pancakes'] 2
['olive oil', 'burgers', 'nan', 'chocolate'] 18
['olive oil', 'burgers', 'nan', 'chocolate', 'chicken'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'fresh tuna'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'fresh tuna', 'parmesan cheese'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'tomatoes'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'ham'] 3
['olive oil', 'burgers', 'nan', 'chocolate', 'ham', 'pancakes'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'ham', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'ham', 'grated cheese'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'ham', 'grated cheese', 'cake'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'ham', 'cake'] 3
['olive oil', 'burgers', 'nan', 'chocolate', 'pancakes'] 9
['olive oil', 'burgers', 'nan', 'chocolate', 'pancakes', 'parmesan cheese'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'pancakes', 'parmesan cheese', 'cake'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'pancakes', 'cake'] 4
['olive oil', 'burgers', 'nan', 'chocolate', 'pancakes', 'muffins'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'grated cheese'] 3
['olive oil', 'burgers', 'nan', 'chocolate', 'grated cheese', 'cake'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'parmesan cheese'] 3
['olive oil', 'burgers', 'nan', 'chocolate', 'parmesan cheese', 'cake'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'ground beef'] 3
['olive oil', 'burgers', 'nan', 'chocolate', 'ground beef', 'cake'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'cake'] 7
['olive oil', 'burgers', 'nan', 'chocolate', 'cake', 'muffins'] 2
['olive oil', 'burgers', 'nan', 'chocolate', 'muffins'] 3
['olive oil', 'burgers', 'nan', 'chocolate', 'french wine'] 2
['olive oil', 'burgers', 'nan', 'chicken'] 6
['olive oil', 'burgers', 'nan', 'chicken', 'pancakes'] 2
['olive oil', 'burgers', 'nan', 'chicken', 'cake'] 2
['olive oil', 'burgers', 'nan', 'oil'] 2
['olive oil', 'burgers', 'nan', 'fresh tuna'] 4
['olive oil', 'burgers', 'nan', 'fresh tuna', 'grated cheese'] 2
['olive oil', 'burgers', 'nan', 'fresh tuna', 'parmesan cheese'] 2
['olive oil', 'burgers', 'nan', 'fresh tuna', 'cake'] 2
['olive oil', 'burgers', 'nan', 'tomatoes'] 5
['olive oil', 'burgers', 'nan', 'tomatoes', 'protein bar'] 3
['olive oil', 'burgers', 'nan', 'tomatoes', 'cake'] 2
['olive oil', 'burgers', 'nan', 'extra dark chocolate'] 2
['olive oil', 'burgers', 'nan', 'protein bar'] 5
['olive oil', 'burgers', 'nan', 'protein bar', 'grated cheese'] 2
['olive oil', 'burgers', 'nan', 'pasta'] 2
['olive oil', 'burgers', 'nan', 'rice'] 2
['olive oil', 'burgers', 'nan', 'ham'] 4
['olive oil', 'burgers', 'nan', 'ham', 'pancakes'] 2
['olive oil', 'burgers', 'nan', 'ham', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'nan', 'ham', 'grated cheese'] 2
['olive oil', 'burgers', 'nan', 'ham', 'grated cheese', 'cake'] 2
['olive oil', 'burgers', 'nan', 'ham', 'cake'] 3
['olive oil', 'burgers', 'nan', 'pancakes'] 12
['olive oil', 'burgers', 'nan', 'pancakes', 'parmesan cheese'] 2
['olive oil', 'burgers', 'nan', 'pancakes', 'parmesan cheese', 'cake'] 2
['olive oil', 'burgers', 'nan', 'pancakes', 'ground beef'] 2
['olive oil', 'burgers', 'nan', 'pancakes', 'cake'] 5
['olive oil', 'burgers', 'nan', 'pancakes', 'muffins'] 2
['olive oil', 'burgers', 'nan', 'pancakes', 'french wine'] 2
['olive oil', 'burgers', 'nan', 'pancakes', 'fromage blanc'] 2
['olive oil', 'burgers', 'nan', 'grated cheese'] 6
['olive oil', 'burgers', 'nan', 'grated cheese', 'ground beef'] 2
['olive oil', 'burgers', 'nan', 'grated cheese', 'cake'] 2
['olive oil', 'burgers', 'nan', 'parmesan cheese'] 3
['olive oil', 'burgers', 'nan', 'parmesan cheese', 'cake'] 2
['olive oil', 'burgers', 'nan', 'fresh bread'] 2
['olive oil', 'burgers', 'nan', 'ground beef'] 10
['olive oil', 'burgers', 'nan', 'ground beef', 'escalope'] 2
['olive oil', 'burgers', 'nan', 'ground beef', 'cake'] 4
['olive oil', 'burgers', 'nan', 'escalope'] 3
['olive oil', 'burgers', 'nan', 'tomato sauce'] 2
['olive oil', 'burgers', 'nan', 'cake'] 12
['olive oil', 'burgers', 'nan', 'cake', 'muffins'] 2
['olive oil', 'burgers', 'nan', 'hot dogs'] 2
['olive oil', 'burgers', 'nan', 'brownies'] 2
['olive oil', 'burgers', 'nan', 'cereals'] 2
['olive oil', 'burgers', 'nan', 'muffins'] 3
['olive oil', 'burgers', 'nan', 'light mayo'] 3
['olive oil', 'burgers', 'nan', 'gums'] 3
['olive oil', 'burgers', 'nan', 'gums', 'french wine'] 2
['olive oil', 'burgers', 'nan', 'french wine'] 4
['olive oil', 'burgers', 'nan', 'french wine', 'salt'] 2
['olive oil', 'burgers', 'nan', 'salt'] 2
['olive oil', 'burgers', 'nan', 'mayonnaise'] 2
['olive oil', 'burgers', 'nan', 'fromage blanc'] 2
['olive oil', 'burgers', 'nan', 'hand protein bar'] 2
['olive oil', 'burgers', 'turkey'] 9
['olive oil', 'burgers', 'turkey', 'milk'] 4
['olive oil', 'burgers', 'turkey', 'milk', 'french fries'] 2
['olive oil', 'burgers', 'turkey', 'milk', 'ground beef'] 2
['olive oil', 'burgers', 'turkey', 'french fries'] 4
['olive oil', 'burgers', 'turkey', 'french fries', 'spaghetti'] 3
['olive oil', 'burgers', 'turkey', 'french fries', 'spaghetti', 'chocolate'] 2
['olive oil', 'burgers', 'turkey', 'french fries', 'chocolate'] 2
['olive oil', 'burgers', 'turkey', 'soup'] 2
['olive oil', 'burgers', 'turkey', 'frozen vegetables'] 2
['olive oil', 'burgers', 'turkey', 'spaghetti'] 4
['olive oil', 'burgers', 'turkey', 'spaghetti', 'chocolate'] 2
['olive oil', 'burgers', 'turkey', 'cooking oil'] 2
['olive oil', 'burgers', 'turkey', 'cooking oil', 'chocolate'] 2
['olive oil', 'burgers', 'turkey', 'chocolate'] 4
['olive oil', 'burgers', 'turkey', 'pancakes'] 2
['olive oil', 'burgers', 'turkey', 'ground beef'] 2
['olive oil', 'burgers', 'turkey', 'cake'] 2
['olive oil', 'burgers', 'milk'] 18
['olive oil', 'burgers', 'milk', 'whole wheat rice'] 2
['olive oil', 'burgers', 'milk', 'whole wheat rice', 'spaghetti'] 2
['olive oil', 'burgers', 'milk', 'whole wheat rice', 'spaghetti', 'protein bar'] 2
['olive oil', 'burgers', 'milk', 'whole wheat rice', 'protein bar'] 2
['olive oil', 'burgers', 'milk', 'whole wheat pasta'] 2
['olive oil', 'burgers', 'milk', 'whole wheat pasta', 'chicken'] 2
['olive oil', 'burgers', 'milk', 'whole wheat pasta', 'chicken', 'pancakes'] 2
['olive oil', 'burgers', 'milk', 'whole wheat pasta', 'pancakes'] 2
['olive oil', 'burgers', 'milk', 'french fries'] 4
['olive oil', 'burgers', 'milk', 'french fries', 'spaghetti'] 2
['olive oil', 'burgers', 'milk', 'french fries', 'oil'] 2
['olive oil', 'burgers', 'milk', 'french fries', 'ground beef'] 2
['olive oil', 'burgers', 'milk', 'soup'] 6
['olive oil', 'burgers', 'milk', 'soup', 'frozen vegetables'] 2
['olive oil', 'burgers', 'milk', 'soup', 'spaghetti'] 2
['olive oil', 'burgers', 'milk', 'soup', 'pancakes'] 2
['olive oil', 'burgers', 'milk', 'soup', 'pancakes', 'fromage blanc'] 2
['olive oil', 'burgers', 'milk', 'soup', 'ground beef'] 3
['olive oil', 'burgers', 'milk', 'soup', 'fromage blanc'] 2
['olive oil', 'burgers', 'milk', 'frozen vegetables'] 4
['olive oil', 'burgers', 'milk', 'spaghetti'] 9
['olive oil', 'burgers', 'milk', 'spaghetti', 'chocolate'] 4
['olive oil', 'burgers', 'milk', 'spaghetti', 'chocolate', 'ground beef'] 3
['olive oil', 'burgers', 'milk', 'spaghetti', 'chocolate', 'ground beef', 'cake'] 2
['olive oil', 'burgers', 'milk', 'spaghetti', 'chocolate', 'cake'] 2
['olive oil', 'burgers', 'milk', 'spaghetti', 'chicken'] 4
['olive oil', 'burgers', 'milk', 'spaghetti', 'protein bar'] 2
['olive oil', 'burgers', 'milk', 'spaghetti', 'pancakes'] 2
['olive oil', 'burgers', 'milk', 'spaghetti', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'milk', 'spaghetti', 'ground beef'] 4
['olive oil', 'burgers', 'milk', 'spaghetti', 'ground beef', 'cake'] 2
['olive oil', 'burgers', 'milk', 'spaghetti', 'cake'] 3
['olive oil', 'burgers', 'milk', 'chocolate'] 7
['olive oil', 'burgers', 'milk', 'chocolate', 'chicken'] 2
['olive oil', 'burgers', 'milk', 'chocolate', 'pancakes'] 3
['olive oil', 'burgers', 'milk', 'chocolate', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'milk', 'chocolate', 'ground beef'] 3
['olive oil', 'burgers', 'milk', 'chocolate', 'ground beef', 'cake'] 2
['olive oil', 'burgers', 'milk', 'chocolate', 'cake'] 3
['olive oil', 'burgers', 'milk', 'chicken'] 5
['olive oil', 'burgers', 'milk', 'chicken', 'pancakes'] 2
['olive oil', 'burgers', 'milk', 'oil'] 2
['olive oil', 'burgers', 'milk', 'protein bar'] 2
['olive oil', 'burgers', 'milk', 'pancakes'] 5
['olive oil', 'burgers', 'milk', 'pancakes', 'ground beef'] 2
['olive oil', 'burgers', 'milk', 'pancakes', 'cake'] 3
['olive oil', 'burgers', 'milk', 'pancakes', 'fromage blanc'] 2
['olive oil', 'burgers', 'milk', 'grated cheese'] 2
['olive oil', 'burgers', 'milk', 'grated cheese', 'ground beef'] 2
['olive oil', 'burgers', 'milk', 'ground beef'] 8
['olive oil', 'burgers', 'milk', 'ground beef', 'cake'] 3
['olive oil', 'burgers', 'milk', 'cake'] 6
['olive oil', 'burgers', 'milk', 'light mayo'] 2
['olive oil', 'burgers', 'milk', 'fromage blanc'] 2
['olive oil', 'burgers', 'energy bar'] 2
['olive oil', 'burgers', 'whole wheat rice'] 4
['olive oil', 'burgers', 'whole wheat rice', 'french fries'] 2
['olive oil', 'burgers', 'whole wheat rice', 'french fries', 'spaghetti'] 2
['olive oil', 'burgers', 'whole wheat rice', 'spaghetti'] 3
['olive oil', 'burgers', 'whole wheat rice', 'spaghetti', 'protein bar'] 2
['olive oil', 'burgers', 'whole wheat rice', 'chocolate'] 2
['olive oil', 'burgers', 'whole wheat rice', 'protein bar'] 2
['olive oil', 'burgers', 'whole wheat pasta'] 9
['olive oil', 'burgers', 'whole wheat pasta', 'chocolate'] 2
['olive oil', 'burgers', 'whole wheat pasta', 'chicken'] 3
['olive oil', 'burgers', 'whole wheat pasta', 'chicken', 'pancakes'] 2
['olive oil', 'burgers', 'whole wheat pasta', 'chicken', 'cake'] 2
['olive oil', 'burgers', 'whole wheat pasta', 'pancakes'] 2
['olive oil', 'burgers', 'whole wheat pasta', 'cake'] 2
['olive oil', 'burgers', 'french fries'] 11
['olive oil', 'burgers', 'french fries', 'soup'] 2
['olive oil', 'burgers', 'french fries', 'frozen vegetables'] 3
['olive oil', 'burgers', 'french fries', 'spaghetti'] 7
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate'] 5
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'fresh tuna'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'fresh tuna', 'parmesan cheese'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'ham'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'ham', 'pancakes'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'ham', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'ham', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'pancakes'] 3
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'parmesan cheese'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'cake'] 3
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'cake', 'muffins'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'chocolate', 'muffins'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'fresh tuna'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'fresh tuna', 'parmesan cheese'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'protein bar'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'ham'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'ham', 'pancakes'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'ham', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'ham', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'pancakes'] 3
['olive oil', 'burgers', 'french fries', 'spaghetti', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'parmesan cheese'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'cake'] 3
['olive oil', 'burgers', 'french fries', 'spaghetti', 'cake', 'muffins'] 2
['olive oil', 'burgers', 'french fries', 'spaghetti', 'muffins'] 2
['olive oil', 'burgers', 'french fries', 'chocolate'] 5
['olive oil', 'burgers', 'french fries', 'chocolate', 'fresh tuna'] 2
['olive oil', 'burgers', 'french fries', 'chocolate', 'fresh tuna', 'parmesan cheese'] 2
['olive oil', 'burgers', 'french fries', 'chocolate', 'ham'] 2
['olive oil', 'burgers', 'french fries', 'chocolate', 'ham', 'pancakes'] 2
['olive oil', 'burgers', 'french fries', 'chocolate', 'ham', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'chocolate', 'ham', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'chocolate', 'pancakes'] 3
['olive oil', 'burgers', 'french fries', 'chocolate', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'chocolate', 'parmesan cheese'] 2
['olive oil', 'burgers', 'french fries', 'chocolate', 'cake'] 3
['olive oil', 'burgers', 'french fries', 'chocolate', 'cake', 'muffins'] 2
['olive oil', 'burgers', 'french fries', 'chocolate', 'muffins'] 2
['olive oil', 'burgers', 'french fries', 'oil'] 2
['olive oil', 'burgers', 'french fries', 'fresh tuna'] 2
['olive oil', 'burgers', 'french fries', 'fresh tuna', 'parmesan cheese'] 2
['olive oil', 'burgers', 'french fries', 'protein bar'] 3
['olive oil', 'burgers', 'french fries', 'protein bar', 'grated cheese'] 2
['olive oil', 'burgers', 'french fries', 'ham'] 2
['olive oil', 'burgers', 'french fries', 'ham', 'pancakes'] 2
['olive oil', 'burgers', 'french fries', 'ham', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'ham', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'pancakes'] 4
['olive oil', 'burgers', 'french fries', 'pancakes', 'cake'] 2
['olive oil', 'burgers', 'french fries', 'grated cheese'] 2
['olive oil', 'burgers', 'french fries', 'parmesan cheese'] 2
['olive oil', 'burgers', 'french fries', 'ground beef'] 2
['olive oil', 'burgers', 'french fries', 'cake'] 3
['olive oil', 'burgers', 'french fries', 'cake', 'muffins'] 2
['olive oil', 'burgers', 'french fries', 'muffins'] 2
['olive oil', 'burgers', 'soup'] 11
['olive oil', 'burgers', 'soup', 'frozen vegetables'] 3
['olive oil', 'burgers', 'soup', 'spaghetti'] 3
['olive oil', 'burgers', 'soup', 'chocolate'] 2
['olive oil', 'burgers', 'soup', 'chocolate', 'cake'] 2
['olive oil', 'burgers', 'soup', 'pancakes'] 2
['olive oil', 'burgers', 'soup', 'pancakes', 'fromage blanc'] 2
['olive oil', 'burgers', 'soup', 'ground beef'] 3
['olive oil', 'burgers', 'soup', 'cake'] 2
['olive oil', 'burgers', 'soup', 'light mayo'] 2
['olive oil', 'burgers', 'soup', 'fromage blanc'] 2
['olive oil', 'burgers', 'frozen vegetables'] 11
['olive oil', 'burgers', 'frozen vegetables', 'spaghetti'] 4

In [8]:
import pandas as pd

df_results = pd.DataFrame(results, columns=["Itemset", "Support"])
df_results

                                                  Itemset  Support
0                                                [shrimp]      536
1                                       [shrimp, almonds]       17
2                              [shrimp, almonds, avocado]        2
3                   [shrimp, almonds, avocado, green tea]        2
4       [shrimp, almonds, avocado, green tea, frozen s...        2
...                                                   ...      ...
213093                                          [bramble]       14
213094                                     [burger sauce]       44
213095                                          [oatmeal]       33
213096                                            [cream]        7
213097                                          [napkins]        5

[213098 rows x 2 columns]